#!/usr/bin/env bash
set -e

# TODO
# Parse input for version tag
# Make sure docker exists

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
APP_DIR=`realpath "$SCRIPTS_DIR/.."`
REPO_DIR=`realpath "$APP_DIR/.."`

(cd $REPO_DIR && docker build -t bstoots/wowhead-item-roulette:latest .)
